import {
  MatButtonModule,
  MatCheckboxModule,
  MatMenuModule,
  MatToolbarModule,
  MatBadgeModule,
  MatIconModule,
  MatProgressSpinnerModule,
  MatSelectModule,
  MatSlideToggleModule,
  MatCardModule,
  MatDividerModule,
  MatExpansionModule,
  MatGridListModule,
  MatListModule,
  MatStepperModule,
  MatTabsModule,
  MatDialogModule,
  MatTooltipModule,
  MatPaginatorModule,
  MatTableModule,
  MatSortModule,
  MatDatepickerModule,
  MatFormFieldModule,
  MatInputModule
 }
 from '@angular/material';
 import { HttpClientModule } from "@angular/common/http";

import {NgModule} from '@angular/core';

@NgModule({
  imports: [
    HttpClientModule,
    MatButtonModule,
     MatCheckboxModule,
      MatMenuModule,
      MatToolbarModule,
      MatBadgeModule,
      MatIconModule,
      MatProgressSpinnerModule,
      MatSelectModule,
      MatSlideToggleModule,
      MatCardModule,
      MatDividerModule,
      MatExpansionModule,
      MatGridListModule,
      MatListModule,
      MatStepperModule,
      MatTabsModule,
      MatDialogModule,
      MatTooltipModule,
      MatPaginatorModule,
      MatTableModule,
      MatSortModule,
      MatDatepickerModule,
      MatFormFieldModule,
      MatInputModule
    ],
  exports: [
    HttpClientModule,
    MatButtonModule,
     MatCheckboxModule,
      MatMenuModule,
      MatToolbarModule,
      MatBadgeModule,
      MatIconModule,
      MatProgressSpinnerModule,
      MatSelectModule,
      MatSlideToggleModule,
      MatCardModule,
      MatDividerModule,
      MatExpansionModule,
      MatGridListModule,
      MatListModule,
      MatStepperModule,
      MatTabsModule,
      MatDialogModule,
      MatTooltipModule,
      MatPaginatorModule,
      MatTableModule,
      MatSortModule,
      MatDatepickerModule,
      MatFormFieldModule,
      MatInputModule
    ],
})

export class MaterialModule{ }
